{{- define "ffc-demo-web.container" -}}
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4 }}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4 }}
{{- end -}}
